# Generated by Django 5.2.3 on 2025-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this blog post', null=True, upload_to='blog_images/'),
        ),
    ]
